### ISSUE TITLE
OS X support

### ISSUE THREAD

**Issue by ben-albrecht** [Rapiz1/chapel-envVariables#1]
What OSes has this module been tested on? I am not able to compile on OS X due to missing header.

**Comment by yujqiao** [comment]
I tested it on Arch Linux.
It's weird because the module does not require any headers other than `c-environ.h`, which is included in the source.
Could you please provide further information?

**Comment by ben-albrecht** [comment]
Sorry, I missed that the headers were included. Using the full mason package, I was able to use it successfully. Thanks!
